"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var auth_middleware_1 = require("../middlewares/auth.middleware");
var question_controller_1 = require("../controllers/question.controller");
var upload_middleware_1 = require("../middlewares/upload.middleware");
var questionRouter = express_1.default.Router();
questionRouter.post('/get', auth_middleware_1.verifyJwt, auth_middleware_1.adminAccess, question_controller_1.default.getQuestions);
questionRouter.post('/create', auth_middleware_1.verifyJwt, auth_middleware_1.adminAccess, upload_middleware_1.default.single('img'), question_controller_1.default.addQuestion);
questionRouter.delete('/:id', auth_middleware_1.verifyJwt, auth_middleware_1.adminAccess, question_controller_1.default.deleteQuestion);
questionRouter.post('/ask-ai/:id', question_controller_1.default.explainUsingAi);
questionRouter.get('/topics', question_controller_1.default.getQuestionTopics);
exports.default = questionRouter;
