"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var user_controller_1 = require("../controllers/user.controller");
var auth_middleware_1 = require("../middlewares/auth.middleware");
var upload_middleware_1 = require("../middlewares/upload.middleware");
var userRouter = express_1.default.Router();
userRouter.post('/register', user_controller_1.default.register);
userRouter.post('/login', user_controller_1.default.login);
userRouter.get('/verify-session', user_controller_1.default.verifySession);
userRouter.get('/generate-otp/:regno', user_controller_1.default.generateOTP);
userRouter.post('/forgot-password', user_controller_1.default.forgotPass);
userRouter.get('/dashboard', auth_middleware_1.verifyJwt, user_controller_1.default.getUserDashboard);
userRouter.post('/update-avatar', auth_middleware_1.verifyJwt, upload_middleware_1.default.single('avatar'), user_controller_1.default.uploadAvatar);
userRouter.post('/block', auth_middleware_1.verifyJwt, auth_middleware_1.jsprAccess, user_controller_1.default.blockUser);
userRouter.post('/unblock', auth_middleware_1.verifyJwt, auth_middleware_1.jsprAccess, user_controller_1.default.unblockUser);
userRouter.get('/blocked', auth_middleware_1.verifyJwt, auth_middleware_1.jsprAccess, user_controller_1.default.getBlockedUsers);
userRouter.post('/add-jsprs', auth_middleware_1.verifyJwt, auth_middleware_1.adminAccess, user_controller_1.default.addJsprs);
userRouter.get('/jsprs', user_controller_1.default.getJsprs);
userRouter.post('/change-password', auth_middleware_1.verifyJwt, user_controller_1.default.changePassword);
userRouter.put('/edit-profile', auth_middleware_1.verifyJwt, user_controller_1.default.editProfile);
userRouter.post('/update-warnings', auth_middleware_1.verifyJwt, user_controller_1.default.updateWarnings);
exports.default = userRouter;
